---
# ansible-playbook -v -i inventories/hosts  main.yml --tags provision
- name: Provision AWS EC2 Instance
  hosts: localhost
  roles:
    - { role: provision-instance }

- name: Update and Reboot instances
  remote_user: root
  vars:
    ansible_ssh_private_key_file:  "{{ ec2_private_key_dir }}"
  hosts: webservers
  roles:
    - { role: update-package-manager }
    - { role: upgrade-packages }
    - { role: reboot }


