---

- name: gather facts
  setup:
    gather_subset: 'min'

- name: Reboot
  shell: sleep 3 && reboot
  async: 45
  poll: 0
  changed_when: False

- name: Wait for SSH to come up
  wait_for_connection:
    delay: 30
    timeout: 120
